name: # Busybox 
description: |
  # Description of the Catalog Entry
version: 1
category: # Category to be used for searching catalog entries
maintainer: Nenggang Pan
license: Apache 2.0 
projectURL: https://github.com/nenggangpan/test-rancher-catalog.git