gitlab-server:
  ports:
  - ${gitlab_exposed_ssh_port}:22
  - ${gitlab_exposed_http_port}:80
  labels:
    io.rancher.sidekicks: gitlab-data
  hostname: ${gitlab_hostname}
  image: gitlab/gitlab-ce:8.5.1-ce.0
  volumes_from:
  - gitlab-data

gitlab-data:
  labels:
    io.rancher.container.start_once: 'true'
  entrypoint:
  - /bin/true
  hostname: gitdata
  image: gitlab/gitlab-ce:8.5.1-ce.0
  volumes:
  - ${GITLAB-CONFIG-DIR}:/etc/gitlab
  - ${GITLAB-LOG-DIR}:/var/log/gitlab
  - ${GITLAB-DATA-DIR}:/var/opt/gitlab
