name:  Graphite Sample
description: Graphite Sample
version: v0.1.0
category: sentience-monitoring
maintainer: Nenggang Pan
license: Apache 2.0 
projectURL: 
#projectURL: https://github.com/nenggangpan/test-rancher-catalog.git
