name:  Registry 2 
description: Registry 2
version: v0.1.0
category: sentience-tools
maintainer: Nenggang Pan
license: Apache 2.0 
projectURL: 
#projectURL: https://github.com/nenggangpan/test-rancher-catalog.git
