name:  Forgerock openam with no pre-configuration. 
description: Forgerock openam with no pre-configuration, and the default configure in the first page is not usable. please use the customer configure.
version: v0.1.0
category: sentience identity server
maintainer: Nenggang Pan
license: Apache 2.0 
projectURL: 
#projectURL: https://github.com/nenggangpan/test-rancher-catalog.git
