name:  PostgreSQL Cluster
description: PostgreSQL Cluster service
version: v0.1.0
category: sentience database
maintainer: Nenggang Pan
license: Apache 2.0 
projectURL: 
#projectURL: https://github.com/nenggangpan/test-rancher-catalog.git
