.catalog:
  name: "Forgerock openam with external opendj"
  version: v0.1.0
  description: "sentience identity component with together with an external opendj"
  minimum_rancher_version: v0.1.0
  questions:
    - variable: exposed_openam_gui_port
      description: "Port used to login openam"
      label: "exposed_openam_gui_port"
      required: true
      default: "8080"
      type: "int"
    - variable: exposed_opendj_port1
      description: "Port 1 for opendj"
      label: "exposed_opendj_port1"
      required: true
      default: "389"
      type: "int"
    - variable: exposed_opendj_port2
      description: "Port 2 for opendj"
      label: "exposed_opendj_port2"
      required: true
      default: "4444"
      type: "int"
    - variable: HOSTNAME_SHORT
      description: "short hostname of openam server"
      label: "HOSTNAME_SHORT"
      required: true
      default: "openam"
      type: "string"
    - variable: CK_DOMAIN
      description: "cookie domain of openam server"
      label: "CK_DOMAIN"
      required: true
      default: ".cookie.domain"
      type: "string"
    - variable: ADMIN_PWD
      description: "password of openam server account amadmin"
      label: "ADMIN_PWD"
      required: true
      default: "password"
      type: "string"
    - variable: DIR_MANAGER_PWD
      description: "Default password for openam config store"
      label: "DIR_MANAGER_PWD"
      required: true
      default: "passwordcs"
      type: "string"
    - variable: IMAGE_TAG
      description: "openam image tag"
      label: "IMAGE_TAG"
      required: true
      default: "latest"
      type: "string"
