name:  Rabbitmq
description: Rabbitmq service
version: v0.1.0
category: sentience-messaging
maintainer: Nenggang Pan
license: Apache 2.0 
projectURL: 
#projectURL: https://github.com/nenggangpan/test-rancher-catalog.git
