openam:
  image: forgerock/openam:$IMAGE_TAG
  hostname: openam
  labels:
  - "io.rancher.container.network=true"  
  ports:
  - "$exposed_openam_gui_port:8080"
  volumes:
  - /dev/urandom:/dev/random
