.catalog:
  name: "Forgerock openam with no pre-configuration"
  version: v0.1.0
  description: "sentience identity component with no pre-configuration, the default configuration in the first page is not usable"
  minimum_rancher_version: v0.1.0
  questions:
    - variable: exposed_openam_gui_port
      description: "Port used to login openam"
      label: "exposed_openam_gui_port"
      required: true
      default: "8080"
      type: "int"
    - variable: IMAGE_TAG
      description: "openam image tag"
      label: "IMAGE_TAG"
      required: true
      default: "latest"
      type: "string"
