.catalog:
  name: "Busybox"
  version: v0.1.0
  description: "busybox tool"
  minimum_rancher_version: v0.1.0
#  questions:
#    - variable: client_port
#      description: "Port to access the blog"
#      label: "Client Port"
#      required: true
#      default: "80"
#      type: "int"
