rabbitserver:
  image: my_rabbitmq:3.5.4
  command: rabbit-server
  ports:
    - $listen_port:5672
    - $management_port:15672
    - $clustering_port_1
    - $clustering_port_2
rabbitnode:
  image: my_rabbitmq:3.5.4
  command: rabbit-node
  ports:
    - $listen_port:5672
    - $management_port:15672
    - $clustering_port_1
    - $clustering_port_2
  
