openam:
  image: forgerock/openam:$IMAGE_TAG
  hostname: openam
#  labels:
#  - "io.rancher.container.network=true"  
  environment:
  - CK_DOMAIN=$CK_DOMAIN
  - HOSTNAME=$HOSTNAME_SHORT$CK_DOMAIN
  - FQDN_HOSTNAME=$HOSTNAME_SHORT$CK_DOMAIN
  - SERVER_URL=http://$HOSTNAME_SHORT$CK_DOMAIN:8080
  - ADMIN_PWD=$ADMIN_PWD
  ports:
  - "$exposed_openam_gui_port:8080"
  volumes:
  - /home/sentience/rancher-openam/sample/am-secrets:/var/secrets/openam
  - /home/sentience/rancher-openam/sample/dj-secrets:/var/secrets/opendj
  - /home/sentience/rancher-openam/sample/config-embedded:/var/tmp/config
