.catalog:
  name: "Forgerock openam with embeded opendj"
  version: v0.1.0
  description: "sentience identity component with embeded opendj"
  minimum_rancher_version: v0.1.0
  questions:
    - variable: exposed_openam_gui_port
      description: "Port used to login openam"
      label: "exposed_openam_gui_port"
      required: true
      default: "8080"
      type: "int"
