.catalog:
  name: "Forgerock openam with embeded opendj"
  version: v0.1.0
  description: "sentience identity component with embeded opendj"
  minimum_rancher_version: v0.1.0
  questions:
    - variable: exposed_openam_gui_port
      description: "Port used to login openam"
      label: "exposed_openam_gui_port"
      required: true
      default: "8080"
      type: "int"
    - variable: HOSTNAME_SHORT
      description: "hostname for short of the web host"
      label: "HOSTNAME_SHORT"
      required: true
      default: "openam"
      type: "string"
    - variable: CK_DOMAIN
      description: "cookie domain of openam server"
      label: "CK_DOMAIN"
      required: true
      default: ".cookie.domain"
      type: "string"
    - variable: ADMIN_PWD
      description: "password for admin account amadmin"
      label: "ADMIN_PWD"
      required: true
      default: "password"
      type: "string"
